const productProvider =[
    {
        id:'1',
        img:'mc',
        name:'Mecurial',
        price:250,
        category:'Mecurial',
    },
    {
        id:'2',
        img:'mc1',
        name:'Mecurial2',
        price:250,
        category:'Mecurial',
    },
    {
        id:'3',
        img:'mc2',
        name:'Mecurial3',
        price:250,
        category:'Mecurial',
    },
    {
        id:'4',
        img:'mc3',
        name:'Mecurial4',
        price:250,
        category:'Mecurial',
    },
    {
        id:'6',
        img:'np',
        name:'Phantom',
        price:350,
        category:'Phantom',
    },
    {
        id:'9',
        img:'np3',
        name:'Phantom2',
        price:350,
        category:'Phantom',
    },
]
export default productProvider